---
title: "Bleeding Events with Enxoaparin in Moderate Renal Dysfunction"
subtitle: "Detailed Results"
author: "Stephanie Kuhl, Brian Gulbis, Andrea C. Hall"
date: "March 24, 2016"
output: html_document
---

```{r}
# library(pander)
source("library.R")
library(rtable)
library(tableone)
library(pander)
panderOptions("table.split.table", Inf)
if (!exists("analyze.demographics")) analyze.demographics <- readRDS(paste(analysis.dir, "demographics.Rds", sep="/"))
```

## FlexTable
```{r results='asis'}
# cat(result_table("html", analyze.demograph, "title"))
res <- result_table("table", analyze.demographics, "title")
res
```

## TableOne

### Categorical
```{r}
x <- create_tableone(analyze.demographics, "group")
x.cat <- print(x$CatTable, printToggle = FALSE)
pander(x.cat)
```

### Cross Tables
```{r}
print(x$CatTable, CrossTable = TRUE)
```

### Continuous Means
```{r}
x.cont <- print(x$ContTable, printToggle = FALSE)
pander(x.cont)
```

### Continuous Medians
```{r}
x.med <- print(x$ContTable, printToggle = FALSE, nonnormal = names(analyze.demographics))
pander(x.med)
```

### Continuous Details
```{r}
summary(x$ContTable)
```
